# Generated by Django 5.2.3 on 2025-06-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_category_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brewingmethod',
            name='contributor',
        ),
        migrations.RemoveField(
            model_name='brewingmethod',
            name='description',
        ),
        migrations.RemoveField(
            model_name='brewingmethod',
            name='recipe',
        ),
        migrations.AddField(
            model_name='brewingmethod',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='method_icons/'),
        ),
    ]
