# Generated by Django 5.2.3 on 2025-06-29 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_category_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='is_iced',
        ),
        migrations.AddField(
            model_name='recipe',
            name='title',
            field=models.CharField(default='Untitled', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='main_app.category'),
        ),
    ]
