# Generated by Django 5.2.3 on 2025-07-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_recipe_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
